import { Aperture, ArrowRight, Badge, BadgeAlert, BadgeCheck, Ban, Banknote, BookOpen, Box, Braces, Calculator, CalendarCheck, CalendarClock, CalendarDays, CalendarRange, Camera, ChartColumn, Clapperboard, ClipboardCheck, CodeXml, Coffee, Compass, Feather, FileCode, FileDown, Flag, Flame, FlaskConical, FolderArchive, Footprints, Funnel, GalleryHorizontal, Gem, Globe, GraduationCap, Handshake, Heading, Heart, Image, Images, Landmark, Layers, LayoutList, LayoutTemplate, Leaf, LifeBuoy, Link, ListChecks, ListTree, MapPin, Megaphone, MessageSquare, Minus, MonitorSmartphone, Mountain, MousePointerClick, NotebookPen, Package, Repeat, Rocket, Route, Scale, Scan, ScanSearch, Search, Shapes, Shield, ShieldCheck, ShoppingBag, ShoppingCart, Smartphone, SquareDashed, Store, Target, Telescope, TrendingUp, Triangle, Trophy, Type, UserRound, VectorSquare, Zap, CircleDot, type LucideIcon } from "lucide-react";

// Icon names used in lib/tools/experience-*.json → components.
const ICONS: Record<string, LucideIcon> = {
  "aperture": Aperture,
  "arrow-right": ArrowRight,
  "badge": Badge,
  "badge-alert": BadgeAlert,
  "badge-check": BadgeCheck,
  "ban": Ban,
  "banknote": Banknote,
  "book-open": BookOpen,
  "box": Box,
  "braces": Braces,
  "calculator": Calculator,
  "calendar-check": CalendarCheck,
  "calendar-clock": CalendarClock,
  "calendar-days": CalendarDays,
  "calendar-range": CalendarRange,
  "camera": Camera,
  "chart-column": ChartColumn,
  "clapperboard": Clapperboard,
  "clipboard-check": ClipboardCheck,
  "code-xml": CodeXml,
  "coffee": Coffee,
  "compass": Compass,
  "feather": Feather,
  "file-code": FileCode,
  "file-down": FileDown,
  "flag": Flag,
  "flame": Flame,
  "flask-conical": FlaskConical,
  "folder-archive": FolderArchive,
  "footprints": Footprints,
  "funnel": Funnel,
  "gallery-horizontal": GalleryHorizontal,
  "gem": Gem,
  "globe": Globe,
  "graduation-cap": GraduationCap,
  "handshake": Handshake,
  "heading": Heading,
  "heart": Heart,
  "image": Image,
  "images": Images,
  "landmark": Landmark,
  "layers": Layers,
  "layout-list": LayoutList,
  "layout-template": LayoutTemplate,
  "leaf": Leaf,
  "life-buoy": LifeBuoy,
  "link": Link,
  "list-checks": ListChecks,
  "list-tree": ListTree,
  "map-pin": MapPin,
  "megaphone": Megaphone,
  "message-square": MessageSquare,
  "minus": Minus,
  "monitor-smartphone": MonitorSmartphone,
  "mountain": Mountain,
  "mouse-pointer-click": MousePointerClick,
  "notebook-pen": NotebookPen,
  "package": Package,
  "repeat": Repeat,
  "rocket": Rocket,
  "route": Route,
  "scale": Scale,
  "scan": Scan,
  "scan-search": ScanSearch,
  "search": Search,
  "shapes": Shapes,
  "shield": Shield,
  "shield-check": ShieldCheck,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  "smartphone": Smartphone,
  "square-dashed": SquareDashed,
  "store": Store,
  "target": Target,
  "telescope": Telescope,
  "trending-up": TrendingUp,
  "triangle": Triangle,
  "trophy": Trophy,
  "type": Type,
  "user-round": UserRound,
  "vector-square": VectorSquare,
  "zap": Zap,
};

export function xIcon(name?: string): LucideIcon {
  return (name && ICONS[name]) || CircleDot;
}
